2019-12-17 01:09:15,316 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:47]
2019-12-17 01:09:44,633 ERROR: Exception on /edit_profile [POST] [in /Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/alokyadav/Python/meershahm/app/routes.py", line 87, in edit_profile
    db.session.commit()
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2470, in flush
    self._flush(objects)
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2568, in _flush
    flush_context.execute()
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 996, in _emit_update_statements
    statement, multiparams
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/Users/alokyadav/Python/meershahm/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('kavya', 'this is test', 2)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2019-12-17 01:34:32,649 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:49]
2019-12-17 01:37:58,771 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:49]
2019-12-22 21:53:59,266 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:49]
2019-12-22 21:58:14,079 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:49]
2019-12-22 22:20:48,836 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:49]
2019-12-22 22:21:21,264 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:49]
2019-12-23 11:04:35,505 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:49]
2019-12-24 10:44:09,449 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:49]
2019-12-30 15:08:10,436 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:49]
2020-01-04 18:34:27,663 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:55]
2020-01-04 18:37:06,620 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:55]
2020-01-05 00:11:52,183 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:60]
2020-01-05 00:13:05,194 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:60]
2020-01-05 01:00:11,027 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:60]
2020-01-05 17:33:40,064 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:60]
2020-01-05 17:34:00,729 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:60]
2020-01-05 22:00:19,408 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:60]
2020-01-05 22:01:02,457 INFO: Meershahm startup [in /Users/alokyadav/Python/meershahm/app/__init__.py:60]
